name: 'Check: Codestyle'

on:
  pull_request:
  workflow_dispatch:

jobs:
  codestyle:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Test MF coding style
        run: |
          cmake -P ./buildscripts/ci/checkcodestyle/checkcodestyle.cmake ./framework/
